default:
  image: 'alpine:latest'
  before_script:
    - apk add curl tar
    - curl -fsSL https://railway.app/install.sh | sh

stages:
  - deploy

deploy to production:
  stage: deploy
  script: railway up
  environment:
    name: production
    url: https://penguinone.kuropen.org/
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy to preview:
  stage: deploy
  script: railway up
  environment:
    name: preview
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
  when: manual
