default:
  image: 'kuropen/railway-cli-docker'

stages:
  - deploy

deploy to production:
  stage: deploy
  script: railway up
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
